run:
  deadline: 10m
  concurrency: 1
  modules-download-mode: readonly
linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - typecheck
    - dupl
    - goconst
    - gofmt
    - revive
    - unconvert
    - gosimple
    - unused
    - staticcheck

issues:
  max-per-linter: 0
  max-same-issues: 0